# Generated by Django 5.2.4 on 2025-07-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_scenariohistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Курсант'), ('teacher', 'Преподаватель')], max_length=10),
        ),
    ]
